# Use the official Node.js image as the base image
FROM node:20-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./

RUN npm install --silent

# Copy app source code
COPY . .

# Expose the port that the backend server will listen on
EXPOSE 9000

# Start the backend server
CMD ["node","--env-file=.env", "index.js"]